server:
  port: 8765



spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: recipes
          uri: lb://api-recipe
          predicates:
            - Path=/recipes/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: ingredients
          uri: lb://api-recipe
          predicates:
            - Path=/ingredients/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,resource.read
        provider:
          spring:
            issuer-uri: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka