server:
  port: 8765

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: recipes
          uri: lb://api-recipe
          predicates:
            - Path=/recipes/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: ingredients
          uri: lb://api-recipe
          predicates:
            - Path=/ingredients/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka