server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  application:
    name: authorization-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'