DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS ingridients CASCADE;
DROP TABLE IF EXISTS recipes_ingredients CASCADE;

CREATE TABLE IF NOT EXISTS recipes(
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR NOT NULL,
    cooking_time TIME,
    portions INTEGER NOT NULL DEFAULT 1,
    rating REAL,
    post_date DATE NOT NULL,
    photo VARCHAR(100) NOT NULL,
    status INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients(
    ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) UNIQUE NOT NULL,
    price REAL,
    photo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS recipes_ingredients(
    recipe_id INTEGER REFERENCES recipes(recipe_id) NOT NULL,
    ingredient_id INTEGER REFERENCES ingredients(ingredient_id) NOT NULL
);