server:
  port: 8081

# tag::client_config[]
# tag::provider_config_0[]
spring:
  application:
    name: client-dotFood
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  security:
    oauth2:
      client:
        # end::provider_config_0[]
        registration:
          client-dotFood:
            provider: client-dotFood
            client-id: client-dotFood
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        # end::client_config[]
        # tag::provider_config[]
        provider:
          client-dotFood:
            issuer-uri: http://127.0.0.1:9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
# end::provider_config[]